### ISSUE TITLE
[Roadmap] Features & Docs

### ISSUE THREAD

**Issue by davidkpiano** [davidkpiano/xstate#742]
## Proposed Features & Enhancements

- [ ] Relative deep targets https://github.com/davidkpiano/xstate/issues/554
- [x] Generic XState Dev Tool support https://github.com/davidkpiano/xstate/issues/709
- [x] (V5) Combine activities & invoked services https://github.com/davidkpiano/xstate/issues/628
- [ ] Expand `@xstate/test` plan strategies https://github.com/davidkpiano/xstate/issues/694
- [x] Microstep listener https://github.com/davidkpiano/xstate/issues/692 https://github.com/davidkpiano/xstate/issues/251
- [ ] Relative paths for in-state guards https://github.com/davidkpiano/xstate/issues/349
- [ ] `@xstate/react` snapshot testing https://github.com/davidkpiano/xstate/issues/432
- [x] Deep `initial` targets https://github.com/davidkpiano/xstate/issues/675
- [x] Actions for `initial` (full config) https://github.com/davidkpiano/xstate/issues/466
- [ ] Abort controller support for `invoke` https://github.com/davidkpiano/xstate/issues/418
- [ ] `@xstate/scxml` SCXML import https://github.com/davidkpiano/xstate/issues/411 https://github.com/davidkpiano/xstate/issues/101
- [x] Split `StateMachine` and `StateNode` https://github.com/davidkpiano/xstate/issues/655
- [ ] Visualizer: cache-bust fetching of gists https://github.com/davidkpiano/xstate/issues/635
- [ ] Expose invoked services https://github.com/davidkpiano/xstate/issues/424
- [ ] sketch.systems to XState https://github.com/davidkpiano/xstate/issues/479
- [ ] Visualizer: support displaying multiple machines https://github.com/davidkpiano/xstate/issues/625
- [ ] Visualizer: TypeScript support https://github.com/davidkpiano/xstate/issues/429
- [ ] XState Storybook addon https://github.com/davidkpiano/xstate/issues/30
- [ ] Design by contract https://github.com/davidkpiano/xstate/issues/183
- [ ] `@xstate/graph` Initial transition https://github.com/davidkpiano/xstate/issues/266
- [ ] Tooling for gradual statechart specification https://github.com/davidkpiano/xstate/issues/287
- [x] `state.done` https://github.com/davidkpiano/xstate/issues/328
- [ ] Visualizer: XState JSON support https://github.com/davidkpiano/xstate/issues/401
- [ ] Visualizer: SVG, ASCII output support https://github.com/davidkpiano/xstate/issues/90
- [ ] Context replace https://github.com/davidkpiano/xstate/issues/262
- [ ] Visualizer: validation https://github.com/davidkpiano/xstate/issues/122
- [ ] Visualizer: meta data https://github.com/davidkpiano/xstate/issues/447
- [ ] Restoring services https://github.com/davidkpiano/xstate/issues/332
- [ ] Visualizer: CLI tool https://github.com/davidkpiano/xstate/issues/528
- [ ] Array conditions https://github.com/davidkpiano/xstate/issues/414
- [ ] Visualize variables of custom guards #881 
- [ ] Visualizer: SSO without GitHub https://github.com/davidkpiano/xstate/issues/751
- [ ] `@xstate/react` React-specific interpreter for concurrent mode https://github.com/davidkpiano/xstate/issues/1094
- [ ] Action arrays https://github.com/davidkpiano/xstate/issues/1104

## Planned Documentation
- [ ] Using `SimulatedClock` with `@xstate/test` https://github.com/davidkpiano/xstate/issues/642
- [ ] Transition execution sequence timing https://github.com/davidkpiano/xstate/issues/621
- [ ] Improve docs on invoking services https://github.com/davidkpiano/xstate/issues/268
- [ ] Pattern for next/back navigation https://github.com/davidkpiano/xstate/issues/188 https://github.com/davidkpiano/xstate/issues/481
- [ ] Using XState in other frameworks (Svelte, Angular, etc.) https://github.com/davidkpiano/xstate/issues/1149
- [ ] Stopping spawned actors https://github.com/davidkpiano/xstate/issues/1116
- [ ] When to use actors https://github.com/davidkpiano/xstate/issues/906

**Comment by CodingDive** [comment]
I'm most excited about the browser extension and visualizing actors 🎉 

Is there a smaller roadmap or expected release date for v4.7?

**Comment by CodingDive** [comment]
Are there any plans for a typed matching API? Whenever I'm refactoring my machines and move state nodes around, I usually need to Ctrl+Shift+F every moved state node to ensure I'm still matching against the correct state structure. It would be great if TypeScript could catch those sort of errors since I'm already defining a state schema for every machine. 😊 

Inspired by @christianalfoni video on how this works in overmind https://www.youtube.com/watch?v=uDS159mWJ58

**Comment by semopz** [comment]
Going forward, could you link us to to a relevant announcement as you complete these tasks? If the link is to a release notes section where multiple features have been introduced, it should be made clear which roadmap item the feature relates to. 

So when I visit this page, I'd like to know
1. Has the feature been implemented (available now via checkboxes 👍)
2. Deps for the feature (e.g., you need xstate v4.7+ AND @xstate/react v1.0+)
3. How to use the feature (examples, API docs link, etc...)
4. The name of the implemented feature. For example `Visualizer: support displaying multiple machines #625` will probably become the `Support for the Actors model in viz` feature (or something to that effect)

**Comment by ThaddeusJiang** [comment]
Hi @davidkpiano 
Could we writing a real world Testing Example.
like your talking https://www.youtube.com/watch?v=tpNmPKjPSFQ
